### ISSUE TITLE
Hardmode ores are inverted [0.6.1]

### ISSUE THREAD

**Issue by SShinkun** [JavidPack/TerraCustom#26]
Creating a world with cobalt, orichalcum and titanium actually generates palladium, mythril and adamantite instead.
(I believe you maintain TEdit too, this application has the same problem, by the time you read this there will be an issue opened there too if there hasn't already.)

**Comment by JavidPack** [comment]
K, the issue is that pre smash altars by default generates the opposite set of ores because the idea was that most people would want both if they were pre smashing, and in-game smashing would result in the other ores. I've fixed this by explicitly letting the user choose to pre-smash and spawn the chosen set instead via an option
